GRANT SELECT, INSERT ON *.* TO 'store'@'localhost' IDENTIFIED BY 'store';

CREATE TABLE Products (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Name TINYTEXT NOT NULL, 
    Description TEXT,
    BrandID INT NOT NULL,
    Price FLOAT NOT NULL, 
    Rating FLOAT, 
    RatingCount INT DEFAULT 0,
    ImagePath TINYTEXT,
    Trending BOOLEAN NOT Null DEFAULT 0,
    Category TINYTEXT,
    FOREIGN KEY (BrandID) 
        REFERENCES Brands (ID) 
        ON DELETE CASCADE
);

CREATE TABLE Brands (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name TINYTEXT NOT NULL,
    LogoPath TINYTEXT
);

CREATE TABLE Orders (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName TINYTEXT NOT NULL,
    LastName TINYTEXT NOT NULL,
    AddressLine1 TINYTEXT,
    AddressLine2 TINYTEXT,
    City TINYTEXT,
    State TINYTEXT,
    Zipcode TINYTEXT
);

CREATE TABLE OrderItems (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE CASCADE
);

CREATE TABLE Outfits (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name TINYTEXT
);

CREATE TABLE OutfitItems(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OutfitID INT NOT NULL,
    ProductID INT NOT NULL,
    FOREIGN KEY (OutfitID) REFERENCES Outfits(ID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE CASCADE
);

CREATE TABLE Users(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username TINYTEXT NOT NULL,
    Password CHAR(40)
)